POST http://localhost:5000/api/collectors/ HTTP/1.1
content-type: application/json

{
    "name": "James Bond",
    "email": "james.bond@mi6.gov.uk",
    "cars": "Aston Martin, BMW",
    "slogan": "Live and let die",
    "trading": false
}